### ISSUE TITLE
fatal java exception in CobolTextDocumentService on "new" editos

### ISSUE THREAD

**Issue by GitMensch** [eclipse/che-che4z-lsp-for-cobol#1773]
## Description ##
Opening an empty editor raises an exception

## Steps to reproduce ##
1. open a new editor., for example with [CTRL]+[N]
2. change the editor-language from "text-only" to "COBOL"
3. insert a space (or anything else)
4. get the error

## Expected behavior ##
The language service should work on the editor content, not on a file, and also work fine with unsaved editors. If a filename is searched to get an "external program-id" or similar then the language server should check for a file (there's likely an api for this, otherwise by wrapping the exception) and if it isn't there just take over the prorgam-id from the content (which may not be typed in yet either).

## Log ##
~~~
[Error - 08:32:29] Request textDocument/documentSymbol failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.nio.file.FileSystemNotFoundException: Provider "untitled" not installed
	at java.base/java.nio.file.Path.of(Path.java:212)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at org.eclipse.lsp.cobol.common.file.WorkspaceFileService.getPathFromURI(WorkspaceFileService.java:93)
	at org.eclipse.lsp.cobol.service.CobolTextDocumentService.documentSymbol(CobolTextDocumentService.java:651)
	... 16 more
~~~

## Environment ##
newest vscode (1.75) and `BroadcomMFD.cobol-language-support` (1.2.0)

## Additional information ##
After updating both (I'd blame the extension) this issue was seen first.

**Comment by GitMensch** [comment]
Rechecked: downgrading to 1.1.1 solves the issue. If 2.0.0 is "a longer way" and you know how to fix this, then a 1.1.3 (1.1.2 is tagged-but-not-released) would be useful.

**Comment by zimlu02** [comment]
Thanks for reporting this issue. 
We will address this in a patch release 1.2.1.

**Comment by zimlu02** [comment]
Fixed in [v1.2.1](https://github.com/eclipse/che-che4z-lsp-for-cobol/releases/tag/1.2.1)
